site_name: swctools
site_description: Jupyter-first toolbox for SWC parsing, modeling, analysis, geometry, and 3D visualization
repo_url: https://github.com/jmrfox/swctools
site_url: https://jmrfox.github.io/swctools/

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - Visualization: visualization.md
  - Installation: install.md
  - API: api.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
